export interface Business {
  id: string
  name: string
  registrationNumber: string
  type: string
  status: "Active" | "Suspended" | "Dissolved"
  district: string
  address: string
  phone: string
  email: string
  website?: string
  registrationDate: string
  description: string
  employees?: number
  verified: boolean
  socialMedia?: {
    facebook?: string
    twitter?: string
    linkedin?: string
  }
  businessHours?: string
  history?: Array<{
    date: string
    event: string
    description: string
  }>
}

export const BUSINESS_TYPES = [
  "Limited Company",
  "NGO",
  "Sole Proprietorship",
  "Partnership",
  "Cooperative",
  "Government Agency",
  "International Organization",
]

export const DISTRICTS = [
  // Western Area
  "Western Area Urban",
  "Western Area Rural",
  // Northern Province
  "Bombali",
  "Kambia",
  "Koinadugu",
  "Port Loko",
  "Tonkolili",
  // Southern Province
  "Bo",
  "Bonthe",
  "Moyamba",
  "Pujehun",
  // Eastern Province
  "Kailahun",
  "Kenema",
  "Kono",
]

export const DEMO_BUSINESSES: Business[] = [
  {
    id: "1",
    name: "Freetown General Trading Ltd",
    registrationNumber: "SL-2020-0001",
    type: "Limited Company",
    status: "Active",
    district: "Western Area Urban",
    address: "15 Siaka Stevens Street, Freetown",
    phone: "+232 76 123456",
    email: "info@fgtl.sl",
    website: "https://fgtl.sl",
    registrationDate: "2020-01-15",
    description: "General import and export trading company specializing in consumer goods",
    employees: 45,
    verified: true,
    socialMedia: {
      facebook: "fgtl",
      linkedin: "freetown-general-trading",
    },
    businessHours: "Mon-Fri: 8:00 AM - 5:00 PM, Sat: 9:00 AM - 2:00 PM",
    history: [
      {
        date: "2024-01-10",
        event: "Verification Renewed",
        description: "Business verification renewed for 2024",
      },
      {
        date: "2023-01-05",
        event: "Address Updated",
        description: "Business address updated to current location",
      },
      {
        date: "2020-01-15",
        event: "Registration",
        description: "Business officially registered",
      },
    ],
  },
  {
    id: "2",
    name: "Sierra Leone Development Foundation",
    registrationNumber: "SL-NGO-2018-0045",
    type: "NGO",
    status: "Active",
    district: "Western Area Urban",
    address: "88 Wilkinson Road, Freetown",
    phone: "+232 77 234567",
    email: "contact@sldf.org",
    website: "https://sldf.org",
    registrationDate: "2018-06-20",
    description: "Non-profit organization focused on community development and education",
    employees: 25,
    verified: true,
    businessHours: "Mon-Fri: 9:00 AM - 5:00 PM",
    history: [
      {
        date: "2023-06-20",
        event: "5-Year Anniversary",
        description: "Celebrated 5 years of service",
      },
      {
        date: "2018-06-20",
        event: "Registration",
        description: "NGO officially registered",
      },
    ],
  },
  {
    id: "3",
    name: "Bo Agricultural Supplies",
    registrationNumber: "SL-2019-0234",
    type: "Limited Company",
    status: "Active",
    district: "Bo",
    address: "12 Kakua Road, Bo",
    phone: "+232 78 345678",
    email: "info@boagricsupplies.sl",
    registrationDate: "2019-03-10",
    description: "Agricultural equipment and supplies distributor",
    employees: 15,
    verified: true,
    businessHours: "Mon-Sat: 7:00 AM - 6:00 PM",
    history: [
      {
        date: "2022-05-12",
        event: "Expansion",
        description: "Opened new branch in Kenema",
      },
      {
        date: "2019-03-10",
        event: "Registration",
        description: "Business officially registered",
      },
    ],
  },
  {
    id: "4",
    name: "Makeni Tech Solutions",
    registrationNumber: "SL-2021-0567",
    type: "Limited Company",
    status: "Active",
    district: "Bombali",
    address: "45 Rogbere Road, Makeni",
    phone: "+232 79 456789",
    email: "hello@makenitecsol.com",
    website: "https://makenitecsol.com",
    registrationDate: "2021-08-15",
    description: "IT services and software development company",
    employees: 12,
    verified: true,
    socialMedia: {
      facebook: "makenitecsol",
      twitter: "makenitecsol",
      linkedin: "makeni-tech-solutions",
    },
    businessHours: "Mon-Fri: 8:30 AM - 5:30 PM",
    history: [
      {
        date: "2023-11-01",
        event: "Product Launch",
        description: "Launched new mobile app platform",
      },
      {
        date: "2021-08-15",
        event: "Registration",
        description: "Business officially registered",
      },
    ],
  },
  {
    id: "5",
    name: "Kenema Mining Corporation",
    registrationNumber: "SL-2017-0089",
    type: "Limited Company",
    status: "Active",
    district: "Kenema",
    address: "23 Hangha Road, Kenema",
    phone: "+232 76 567890",
    email: "info@kenemamining.sl",
    registrationDate: "2017-11-22",
    description: "Diamond mining and mineral exploration",
    employees: 120,
    verified: true,
    businessHours: "Mon-Fri: 7:00 AM - 5:00 PM",
    history: [
      {
        date: "2024-01-15",
        event: "License Renewed",
        description: "Mining license renewed for 3 years",
      },
      {
        date: "2017-11-22",
        event: "Registration",
        description: "Business officially registered",
      },
    ],
  },
  {
    id: "6",
    name: "Port Loko Health Initiative",
    registrationNumber: "SL-NGO-2020-0123",
    type: "NGO",
    status: "Active",
    district: "Port Loko",
    address: "7 Mahera Road, Port Loko",
    phone: "+232 77 678901",
    email: "info@plhi.org",
    registrationDate: "2020-04-10",
    description: "Healthcare NGO providing medical services and health education",
    employees: 30,
    verified: true,
    businessHours: "Mon-Sat: 8:00 AM - 4:00 PM",
    history: [
      {
        date: "2023-04-10",
        event: "3-Year Anniversary",
        description: "Reached 10,000 patients served milestone",
      },
      {
        date: "2020-04-10",
        event: "Registration",
        description: "NGO officially registered",
      },
    ],
  },
  {
    id: "7",
    name: "Kambia Rice Farmers Cooperative",
    registrationNumber: "SL-2019-0445",
    type: "Cooperative",
    status: "Active",
    district: "Kambia",
    address: "34 Rokupr Road, Kambia",
    phone: "+232 78 789012",
    email: "contact@kambiarice.sl",
    registrationDate: "2019-07-05",
    description: "Agricultural cooperative for rice farmers",
    employees: 8,
    verified: true,
    businessHours: "Mon-Sat: 7:00 AM - 5:00 PM",
    history: [
      {
        date: "2023-09-15",
        event: "Expansion",
        description: "Added 50 new member farmers",
      },
      {
        date: "2019-07-05",
        event: "Registration",
        description: "Cooperative officially registered",
      },
    ],
  },
  {
    id: "8",
    name: "Bonthe Island Fisheries Ltd",
    registrationNumber: "SL-2018-0678",
    type: "Limited Company",
    status: "Suspended",
    district: "Bonthe",
    address: "12 Waterfront, Bonthe Island",
    phone: "+232 76 890123",
    email: "info@bonthefisheries.sl",
    registrationDate: "2018-09-12",
    description: "Commercial fishing and seafood processing",
    employees: 35,
    verified: false,
    businessHours: "Operations suspended",
    history: [
      {
        date: "2023-08-20",
        event: "Suspension",
        description: "License suspended pending compliance review",
      },
      {
        date: "2018-09-12",
        event: "Registration",
        description: "Business officially registered",
      },
    ],
  },
  {
    id: "9",
    name: "Moyamba Education Trust",
    registrationNumber: "SL-NGO-2021-0234",
    type: "NGO",
    status: "Active",
    district: "Moyamba",
    address: "56 Bradford Road, Moyamba",
    phone: "+232 77 901234",
    email: "info@moyambaedu.org",
    website: "https://moyambaedu.org",
    registrationDate: "2021-02-14",
    description: "Educational NGO providing scholarships and learning resources",
    employees: 18,
    verified: true,
    businessHours: "Mon-Fri: 8:00 AM - 5:00 PM",
    history: [
      {
        date: "2024-01-05",
        event: "Milestone",
        description: "Awarded 100th scholarship",
      },
      {
        date: "2021-02-14",
        event: "Registration",
        description: "NGO officially registered",
      },
    ],
  },
  {
    id: "10",
    name: "Kono Diamond Dealers Association",
    registrationNumber: "SL-2016-0234",
    type: "Partnership",
    status: "Active",
    district: "Kono",
    address: "89 Mafinda Road, Koidu",
    phone: "+232 78 012345",
    email: "info@konodiamond.sl",
    registrationDate: "2016-05-20",
    description: "Licensed diamond dealers and exporters",
    employees: 22,
    verified: true,
    businessHours: "Mon-Fri: 9:00 AM - 4:00 PM",
    history: [
      {
        date: "2024-01-10",
        event: "Compliance Check",
        description: "Passed annual compliance audit",
      },
      {
        date: "2016-05-20",
        event: "Registration",
        description: "Business officially registered",
      },
    ],
  },
  {
    id: "11",
    name: "Kailahun Agro Processing",
    registrationNumber: "SL-2020-0890",
    type: "Sole Proprietorship",
    status: "Active",
    district: "Kailahun",
    address: "23 Pendembu Road, Kailahun",
    phone: "+232 79 123456",
    email: "info@kailahunagro.sl",
    registrationDate: "2020-10-08",
    description: "Agricultural products processing and packaging",
    employees: 10,
    verified: true,
    businessHours: "Mon-Sat: 7:00 AM - 6:00 PM",
    history: [
      {
        date: "2023-10-08",
        event: "3-Year Anniversary",
        description: "Expanded processing capacity",
      },
      {
        date: "2020-10-08",
        event: "Registration",
        description: "Business officially registered",
      },
    ],
  },
  {
    id: "12",
    name: "Tonkolili Construction Ltd",
    registrationNumber: "SL-2019-0567",
    type: "Limited Company",
    status: "Active",
    district: "Tonkolili",
    address: "45 Magburaka Highway, Magburaka",
    phone: "+232 76 234567",
    email: "info@tonkoliconstr.sl",
    registrationDate: "2019-12-01",
    description: "Building construction and civil engineering",
    employees: 65,
    verified: true,
    businessHours: "Mon-Fri: 7:00 AM - 5:00 PM",
    history: [
      {
        date: "2023-06-15",
        event: "Major Contract",
        description: "Awarded government infrastructure project",
      },
      {
        date: "2019-12-01",
        event: "Registration",
        description: "Business officially registered",
      },
    ],
  },
  {
    id: "13",
    name: "Pujehun Women's Empowerment Co-op",
    registrationNumber: "SL-2021-0345",
    type: "Cooperative",
    status: "Active",
    district: "Pujehun",
    address: "18 Zimmi Road, Pujehun",
    phone: "+232 77 345678",
    email: "info@pujehunempower.sl",
    registrationDate: "2021-03-08",
    description: "Women's cooperative for craft production and marketing",
    employees: 12,
    verified: true,
    businessHours: "Mon-Sat: 8:00 AM - 5:00 PM",
    history: [
      {
        date: "2023-03-08",
        event: "2-Year Anniversary",
        description: "Reached 200 women members",
      },
      {
        date: "2021-03-08",
        event: "Registration",
        description: "Cooperative officially registered",
      },
    ],
  },
  {
    id: "14",
    name: "Koinadugu Livestock Traders",
    registrationNumber: "SL-2018-0901",
    type: "Partnership",
    status: "Active",
    district: "Koinadugu",
    address: "67 Kabala Road, Kabala",
    phone: "+232 78 456789",
    email: "info@koinadugulivestock.sl",
    registrationDate: "2018-07-25",
    description: "Livestock trading and animal husbandry",
    employees: 14,
    verified: true,
    businessHours: "Mon-Sat: 6:00 AM - 6:00 PM",
    history: [
      {
        date: "2023-07-25",
        event: "5-Year Anniversary",
        description: "Expanded operations to 3 districts",
      },
      {
        date: "2018-07-25",
        event: "Registration",
        description: "Business officially registered",
      },
    ],
  },
  {
    id: "15",
    name: "Western Area Rural Tourism Ltd",
    registrationNumber: "SL-2022-0123",
    type: "Limited Company",
    status: "Active",
    district: "Western Area Rural",
    address: "34 Peninsula Road, Waterloo",
    phone: "+232 79 567890",
    email: "info@waritourism.sl",
    website: "https://waritourism.sl",
    registrationDate: "2022-05-18",
    description: "Tourism services and eco-lodge operations",
    employees: 28,
    verified: true,
    socialMedia: {
      facebook: "waritourism",
      instagram: "waritourism",
    },
    businessHours: "Daily: 8:00 AM - 8:00 PM",
    history: [
      {
        date: "2023-12-01",
        event: "Award",
        description: "Won Best Tourism Operator award",
      },
      {
        date: "2022-05-18",
        event: "Registration",
        description: "Business officially registered",
      },
    ],
  },
  {
    id: "16",
    name: "Freetown Pharmaceuticals Ltd",
    registrationNumber: "SL-2017-0456",
    type: "Limited Company",
    status: "Active",
    district: "Western Area Urban",
    address: "78 Wilkinson Road, Freetown",
    phone: "+232 76 678901",
    email: "info@freetownpharma.sl",
    registrationDate: "2017-09-12",
    description: "Pharmaceutical import and distribution",
    employees: 42,
    verified: true,
    businessHours: "Mon-Fri: 8:00 AM - 6:00 PM, Sat: 9:00 AM - 2:00 PM",
    history: [
      {
        date: "2024-01-20",
        event: "Certification",
        description: "Renewed pharmaceutical distribution license",
      },
      {
        date: "2017-09-12",
        event: "Registration",
        description: "Business officially registered",
      },
    ],
  },
  {
    id: "17",
    name: "Bo Youth Skills Center",
    registrationNumber: "SL-NGO-2019-0567",
    type: "NGO",
    status: "Active",
    district: "Bo",
    address: "90 Tikonko Road, Bo",
    phone: "+232 77 789012",
    email: "info@boyouthskills.org",
    registrationDate: "2019-11-05",
    description: "Vocational training and youth development NGO",
    employees: 22,
    verified: true,
    businessHours: "Mon-Sat: 8:00 AM - 5:00 PM",
    history: [
      {
        date: "2023-11-05",
        event: "4-Year Anniversary",
        description: "Trained 500+ youth in various skills",
      },
      {
        date: "2019-11-05",
        event: "Registration",
        description: "NGO officially registered",
      },
    ],
  },
  {
    id: "18",
    name: "United Mining Services",
    registrationNumber: "SL-2015-0123",
    type: "Limited Company",
    status: "Dissolved",
    district: "Kono",
    address: "56 Former Mine Road, Koidu",
    phone: "+232 78 890123",
    email: "info@unitmining.sl",
    registrationDate: "2015-03-20",
    description: "Mining equipment rental and services",
    employees: 0,
    verified: false,
    businessHours: "Permanently closed",
    history: [
      {
        date: "2022-12-31",
        event: "Dissolution",
        description: "Business officially dissolved",
      },
      {
        date: "2015-03-20",
        event: "Registration",
        description: "Business officially registered",
      },
    ],
  },
  {
    id: "19",
    name: "Kambia Border Trade Association",
    registrationNumber: "SL-2020-0678",
    type: "Partnership",
    status: "Active",
    district: "Kambia",
    address: "12 Border Crossing Road, Kambia",
    phone: "+232 79 901234",
    email: "info@kambiatrade.sl",
    registrationDate: "2020-06-15",
    description: "Cross-border trade facilitation services",
    employees: 16,
    verified: true,
    businessHours: "Mon-Sat: 7:00 AM - 6:00 PM",
    history: [
      {
        date: "2023-06-15",
        event: "3-Year Anniversary",
        description: "Facilitated trade worth $5M",
      },
      {
        date: "2020-06-15",
        event: "Registration",
        description: "Business officially registered",
      },
    ],
  },
  {
    id: "20",
    name: "Bombali Digital Hub",
    registrationNumber: "SL-2022-0890",
    type: "Sole Proprietorship",
    status: "Active",
    district: "Bombali",
    address: "23 Satellite Road, Makeni",
    phone: "+232 76 012345",
    email: "info@bombalihub.sl",
    website: "https://bombalihub.sl",
    registrationDate: "2022-11-10",
    description: "Digital services and internet cafe",
    employees: 6,
    verified: true,
    socialMedia: {
      facebook: "bombalihub",
      twitter: "bombalihub",
    },
    businessHours: "Daily: 8:00 AM - 9:00 PM",
    history: [
      {
        date: "2023-11-10",
        event: "1-Year Anniversary",
        description: "Served 1000+ customers",
      },
      {
        date: "2022-11-10",
        event: "Registration",
        description: "Business officially registered",
      },
    ],
  },
]
