// Demo data for Career Guidance Module

export const DEMO_UNIVERSITIES = [
  {
    id: "fbc",
    name: "Fourah Bay College",
    location: "Freetown, Western Area",
    type: "Public",
    tuition: "SLL 2.5M - 4M per year",
    coursesCount: 45,
  },
  {
    id: "njala",
    name: "Njala University",
    location: "Bo, Southern Province",
    type: "Public",
    tuition: "SLL 2M - 3.5M per year",
    coursesCount: 38,
  },
  {
    id: "ep",
    name: "Eastern Polytechnic",
    location: "Kenema, Eastern Province",
    type: "Public",
    tuition: "SLL 1.5M - 3M per year",
    coursesCount: 28,
  },
  {
    id: "unimak",
    name: "University of Makeni",
    location: "Makeni, Northern Province",
    type: "Private",
    tuition: "SLL 3M - 5M per year",
    coursesCount: 32,
  },
  {
    id: "ebku",
    name: "Ernest Bai Koroma University",
    location: "Bombali, Northern Province",
    type: "Public",
    tuition: "SLL 2M - 4M per year",
    coursesCount: 35,
  },
]

export const DEMO_COURSES = [
  {
    id: "cs",
    name: "Computer Science",
    faculty: "Pure and Applied Sciences",
    duration: "4 years",
    matchScore: 95,
    whyRecommended: "Based on your strong performance in Mathematics, Physics, and your analytical aptitude",
    minAggregate: 15,
    universities: ["Fourah Bay College", "University of Makeni", "EBKU"],
    tuition: "SLL 3.5M/year",
    requiredSubjects: ["Mathematics (C6+)", "Physics (C6+)"],
  },
  {
    id: "eng",
    name: "Civil Engineering",
    faculty: "Engineering",
    duration: "5 years",
    matchScore: 92,
    whyRecommended: "Your excellent Mathematics and Physics grades make you ideal for engineering",
    minAggregate: 12,
    universities: ["Fourah Bay College", "Eastern Polytechnic"],
    tuition: "SLL 4M/year",
    requiredSubjects: ["Mathematics (C6+)", "Physics (C6+)", "Chemistry (C6+)"],
  },
  {
    id: "medicine",
    name: "Medicine and Surgery",
    faculty: "Medicine and Allied Health Sciences",
    duration: "6 years",
    matchScore: 88,
    whyRecommended: "Your strong science background and aptitude for helping others align perfectly",
    minAggregate: 10,
    universities: ["College of Medicine and Allied Health Sciences"],
    tuition: "SLL 10M/year",
    requiredSubjects: ["Biology (C6+)", "Chemistry (C6+)", "Physics (C6+)"],
  },
  {
    id: "nursing",
    name: "Nursing Science",
    faculty: "Medicine and Allied Health Sciences",
    duration: "4 years",
    matchScore: 85,
    whyRecommended: "Perfect for your interest in healthcare and strong science performance",
    minAggregate: 18,
    universities: ["COMAHS", "Njala University"],
    tuition: "SLL 3M/year",
    requiredSubjects: ["Biology (C6+)", "Chemistry (C6+)"],
  },
  {
    id: "accounting",
    name: "Accounting and Finance",
    faculty: "Management Sciences",
    duration: "4 years",
    matchScore: 83,
    whyRecommended: "Your mathematical skills and analytical thinking suit this field well",
    minAggregate: 20,
    universities: ["Fourah Bay College", "University of Makeni", "Njala University"],
    tuition: "SLL 2.8M/year",
    requiredSubjects: ["Mathematics (C6+)", "Economics/Commerce"],
  },
  {
    id: "law",
    name: "Law (LLB)",
    faculty: "Law",
    duration: "4 years",
    matchScore: 80,
    whyRecommended: "Your strong English and analytical abilities are essential for legal studies",
    minAggregate: 15,
    universities: ["Fourah Bay College"],
    tuition: "SLL 4.5M/year",
    requiredSubjects: ["English Language (C6+)", "Literature/Government"],
  },
  {
    id: "education",
    name: "Education (Secondary)",
    faculty: "Education",
    duration: "4 years",
    matchScore: 78,
    whyRecommended: "Your communication skills and subject knowledge make teaching a great fit",
    minAggregate: 24,
    universities: ["Fourah Bay College", "Njala University", "EBKU"],
    tuition: "SLL 2M/year",
    requiredSubjects: ["English Language (C6+)", "Teaching subject (C6+)"],
  },
  {
    id: "agriculture",
    name: "Agricultural Science",
    faculty: "Agriculture and Food Security",
    duration: "4 years",
    matchScore: 75,
    whyRecommended: "Your science background supports agricultural innovation and food security",
    minAggregate: 22,
    universities: ["Njala University", "EBKU"],
    tuition: "SLL 2.5M/year",
    requiredSubjects: ["Agricultural Science", "Biology/Chemistry"],
  },
  {
    id: "business",
    name: "Business Administration",
    faculty: "Management Sciences",
    duration: "4 years",
    matchScore: 73,
    whyRecommended: "Your leadership aptitude and business acumen indicate management potential",
    minAggregate: 24,
    universities: ["All major universities"],
    tuition: "SLL 2.5M/year",
    requiredSubjects: ["Mathematics (C6+)", "Economics/Commerce"],
  },
  {
    id: "mass-comm",
    name: "Mass Communication",
    faculty: "Arts and Social Sciences",
    duration: "4 years",
    matchScore: 70,
    whyRecommended: "Your communication skills and creativity suit media and journalism",
    minAggregate: 22,
    universities: ["Fourah Bay College", "University of Makeni"],
    tuition: "SLL 2.8M/year",
    requiredSubjects: ["English Language (C6+)", "Literature"],
  },
]

export const DEMO_CAREERS = [
  {
    id: "software-dev",
    title: "Software Developer",
    matchScore: 95,
    salary: "SLL 5M - 15M per year",
    outlook: "High demand",
    relatedCourses: ["Computer Science", "Information Technology", "Software Engineering"],
    skills: ["Programming", "Problem-solving", "Teamwork", "Critical thinking"],
  },
  {
    id: "civil-eng",
    title: "Civil Engineer",
    matchScore: 92,
    salary: "SLL 8M - 20M per year",
    outlook: "High demand",
    relatedCourses: ["Civil Engineering", "Structural Engineering"],
    skills: ["Technical design", "Project management", "Mathematics", "CAD software"],
  },
  {
    id: "doctor",
    title: "Medical Doctor",
    matchScore: 88,
    salary: "SLL 10M - 30M per year",
    outlook: "High demand",
    relatedCourses: ["Medicine and Surgery"],
    skills: ["Diagnosis", "Patient care", "Medical knowledge", "Decision-making"],
  },
  {
    id: "accountant",
    title: "Chartered Accountant",
    matchScore: 83,
    salary: "SLL 4M - 12M per year",
    outlook: "High demand",
    relatedCourses: ["Accounting and Finance", "Business Administration"],
    skills: ["Financial analysis", "Tax knowledge", "Attention to detail", "Excel"],
  },
  {
    id: "nurse",
    title: "Registered Nurse",
    matchScore: 85,
    salary: "SLL 3M - 8M per year",
    outlook: "High demand",
    relatedCourses: ["Nursing Science", "Midwifery"],
    skills: ["Patient care", "Medical procedures", "Empathy", "Communication"],
  },
  {
    id: "lawyer",
    title: "Legal Practitioner",
    matchScore: 80,
    salary: "SLL 6M - 18M per year",
    outlook: "Moderate",
    relatedCourses: ["Law (LLB)"],
    skills: ["Legal research", "Advocacy", "Writing", "Critical analysis"],
  },
  {
    id: "teacher",
    title: "Secondary School Teacher",
    matchScore: 78,
    salary: "SLL 2.5M - 6M per year",
    outlook: "High demand",
    relatedCourses: ["Education (Secondary)", "Subject-specific degrees"],
    skills: ["Teaching", "Communication", "Patience", "Subject expertise"],
  },
  {
    id: "agric",
    title: "Agricultural Officer",
    matchScore: 75,
    salary: "SLL 3M - 8M per year",
    outlook: "High demand",
    relatedCourses: ["Agricultural Science", "Agribusiness"],
    skills: ["Crop management", "Research", "Advisory", "Sustainability"],
  },
]
