export const sierraLeoneDistricts = [
  { name: "Western Urban", region: "Western Area", clinicCount: 45 },
  { name: "Western Rural", region: "Western Area", clinicCount: 23 },
  { name: "Bo", region: "Southern Province", clinicCount: 31 },
  { name: "Bonthe", region: "Southern Province", clinicCount: 12 },
  { name: "Moyamba", region: "Southern Province", clinicCount: 18 },
  { name: "Pujehun", region: "Southern Province", clinicCount: 14 },
  { name: "Kenema", region: "Eastern Province", clinicCount: 28 },
  { name: "Kailahun", region: "Eastern Province", clinicCount: 16 },
  { name: "Kono", region: "Eastern Province", clinicCount: 19 },
  { name: "Bombali", region: "Northern Province", clinicCount: 25 },
  { name: "Kambia", region: "Northern Province", clinicCount: 15 },
  { name: "Koinadugu", region: "Northern Province", clinicCount: 13 },
  { name: "Port Loko", region: "Northern Province", clinicCount: 22 },
  { name: "Tonkolili", region: "Northern Province", clinicCount: 17 },
  { name: "Falaba", region: "Northern Province", clinicCount: 9 },
  { name: "Karene", region: "Northern Province", clinicCount: 11 },
]

export type ClinicType = "Hospital" | "Health Center" | "Clinic" | "Pharmacy" | "Laboratory" | "Maternity Center"

export interface Clinic {
  id: string
  name: string
  type: ClinicType
  category: "Government" | "Private" | "NGO"
  rating: number
  reviewCount: number
  verified: boolean
  address: string
  district: string
  region: string
  phone: string
  email?: string
  website?: string
  hours: string
  is24Hours: boolean
  isOpenNow: boolean
  emergency: boolean
  services: string[]
  facilities: string[]
  paymentMethods: string[]
  about: string
  photos?: string[]
  latitude?: number
  longitude?: number
}

export const clinicServices = [
  "Emergency Care",
  "Maternity Services",
  "Child Healthcare",
  "Vaccination",
  "HIV/AIDS Testing & Treatment",
  "Malaria Treatment",
  "TB Treatment",
  "Dental Services",
  "Eye Care",
  "Surgery",
  "Laboratory Tests",
  "Pharmacy",
  "Mental Health",
  "Outpatient Services",
  "Inpatient Services",
]

export const demoHealthClinics: Clinic[] = [
  {
    id: "1",
    name: "Connaught Hospital",
    type: "Hospital",
    category: "Government",
    rating: 4.2,
    reviewCount: 234,
    verified: true,
    address: "Lightfoot Boston Street, Freetown",
    district: "Western Urban",
    region: "Western Area",
    phone: "076-555-0001",
    email: "info@connaught.sl",
    website: "www.connaughthospital.sl",
    hours: "Open 24/7",
    is24Hours: true,
    isOpenNow: true,
    emergency: true,
    services: ["Emergency Care", "Surgery", "Maternity Services", "Laboratory Tests", "Pharmacy", "Inpatient Services"],
    facilities: ["Parking", "Wheelchair Access", "Air Conditioning", "WiFi", "Cafeteria"],
    paymentMethods: ["Cash", "Insurance", "NHIS Card"],
    about:
      "Connaught Hospital is the largest government hospital in Sierra Leone, providing comprehensive medical services including emergency care, surgery, and specialized treatments.",
  },
  {
    id: "2",
    name: "Ola During Children's Hospital",
    type: "Hospital",
    category: "Government",
    rating: 4.5,
    reviewCount: 189,
    verified: true,
    address: "Pandemba Road, Freetown",
    district: "Western Urban",
    region: "Western Area",
    phone: "076-555-0002",
    email: "info@oladuring.sl",
    hours: "Open 24/7",
    is24Hours: true,
    isOpenNow: true,
    emergency: true,
    services: [
      "Child Healthcare",
      "Emergency Care",
      "Vaccination",
      "Malaria Treatment",
      "Laboratory Tests",
      "Pharmacy",
    ],
    facilities: ["Parking", "Wheelchair Access", "Pediatric Ward", "Play Area"],
    paymentMethods: ["Cash", "Insurance", "NHIS Card", "Mobile Money"],
    about:
      "Specialized children's hospital providing quality pediatric care including emergency services, vaccinations, and treatment for common childhood illnesses.",
  },
  {
    id: "3",
    name: "Princess Christian Maternity Hospital (PCMH)",
    type: "Maternity Center",
    category: "Government",
    rating: 4.3,
    reviewCount: 312,
    verified: true,
    address: "Tower Hill, Freetown",
    district: "Western Urban",
    region: "Western Area",
    phone: "076-555-0003",
    email: "info@pcmh.sl",
    hours: "Open 24/7",
    is24Hours: true,
    isOpenNow: true,
    emergency: true,
    services: ["Maternity Services", "Emergency Care", "Child Healthcare", "Vaccination", "Laboratory Tests"],
    facilities: ["Parking", "Wheelchair Access", "Maternity Ward", "NICU"],
    paymentMethods: ["Cash", "Insurance", "NHIS Card"],
    about:
      "Premier maternity hospital in Sierra Leone, providing comprehensive maternal and newborn care with experienced staff and modern facilities.",
  },
  {
    id: "4",
    name: "34 Military Hospital",
    type: "Hospital",
    category: "Government",
    rating: 4.0,
    reviewCount: 156,
    verified: true,
    address: "Wilberforce, Freetown",
    district: "Western Rural",
    region: "Western Area",
    phone: "076-555-0004",
    hours: "Open 24/7",
    is24Hours: true,
    isOpenNow: true,
    emergency: true,
    services: [
      "Emergency Care",
      "Surgery",
      "Laboratory Tests",
      "Pharmacy",
      "Outpatient Services",
      "Inpatient Services",
    ],
    facilities: ["Parking", "Wheelchair Access", "Air Conditioning"],
    paymentMethods: ["Cash", "Insurance"],
    about:
      "Military hospital providing medical services to military personnel and civilians, with emergency care and general medical services.",
  },
  {
    id: "5",
    name: "Choithram Memorial Hospital",
    type: "Hospital",
    category: "Private",
    rating: 4.7,
    reviewCount: 201,
    verified: true,
    address: "Hill Station, Freetown",
    district: "Western Urban",
    region: "Western Area",
    phone: "076-555-0005",
    email: "info@choithram.sl",
    website: "www.choithram.sl",
    hours: "Mon-Sat: 8:00 AM - 8:00 PM, Sun: 9:00 AM - 5:00 PM",
    is24Hours: false,
    isOpenNow: true,
    emergency: false,
    services: ["Outpatient Services", "Laboratory Tests", "Pharmacy", "Dental Services", "Eye Care", "Surgery"],
    facilities: ["Parking", "Wheelchair Access", "Air Conditioning", "WiFi", "Pharmacy"],
    paymentMethods: ["Cash", "Credit Card", "Insurance", "Mobile Money"],
    about:
      "Modern private hospital offering quality healthcare services with state-of-the-art equipment and experienced medical professionals.",
  },
  {
    id: "6",
    name: "Mercy Hospital",
    type: "Hospital",
    category: "NGO",
    rating: 4.4,
    reviewCount: 178,
    verified: true,
    address: "Goderich, Freetown",
    district: "Western Rural",
    region: "Western Area",
    phone: "076-555-0006",
    email: "info@mercyhospital.sl",
    hours: "Mon-Fri: 8:00 AM - 6:00 PM, Sat: 9:00 AM - 2:00 PM",
    is24Hours: false,
    isOpenNow: true,
    emergency: false,
    services: [
      "Maternity Services",
      "Child Healthcare",
      "HIV/AIDS Testing & Treatment",
      "Laboratory Tests",
      "Pharmacy",
    ],
    facilities: ["Parking", "Wheelchair Access", "Chapel"],
    paymentMethods: ["Cash", "Insurance", "NHIS Card"],
    about: "Faith-based hospital providing affordable healthcare with focus on maternal and child health services.",
  },
  {
    id: "7",
    name: "Bo Government Hospital",
    type: "Hospital",
    category: "Government",
    rating: 4.1,
    reviewCount: 142,
    verified: true,
    address: "32 Coronation Field Road, Bo",
    district: "Bo",
    region: "Southern Province",
    phone: "076-555-0007",
    email: "info@bogovthospital.sl",
    hours: "Open 24/7",
    is24Hours: true,
    isOpenNow: true,
    emergency: true,
    services: ["Emergency Care", "Surgery", "Maternity Services", "Child Healthcare", "Laboratory Tests", "Pharmacy"],
    facilities: ["Parking", "Wheelchair Access", "Generator"],
    paymentMethods: ["Cash", "Insurance", "NHIS Card"],
    about: "Major regional hospital serving Bo and surrounding districts with comprehensive medical services.",
  },
  {
    id: "8",
    name: "Kenema Government Hospital",
    type: "Hospital",
    category: "Government",
    rating: 4.0,
    reviewCount: 128,
    verified: true,
    address: "Hangha Road, Kenema",
    district: "Kenema",
    region: "Eastern Province",
    phone: "076-555-0008",
    hours: "Open 24/7",
    is24Hours: true,
    isOpenNow: true,
    emergency: true,
    services: ["Emergency Care", "Surgery", "Maternity Services", "TB Treatment", "Laboratory Tests", "Pharmacy"],
    facilities: ["Parking", "Wheelchair Access", "Isolation Ward"],
    paymentMethods: ["Cash", "Insurance", "NHIS Card"],
    about:
      "Regional referral hospital for Eastern Province, specializing in infectious disease treatment and emergency care.",
  },
  {
    id: "9",
    name: "Makeni Government Hospital",
    type: "Hospital",
    category: "Government",
    rating: 3.9,
    reviewCount: 115,
    verified: true,
    address: "Magburaka Road, Makeni",
    district: "Bombali",
    region: "Northern Province",
    phone: "076-555-0009",
    hours: "Open 24/7",
    is24Hours: true,
    isOpenNow: true,
    emergency: true,
    services: ["Emergency Care", "Surgery", "Maternity Services", "Malaria Treatment", "Laboratory Tests", "Pharmacy"],
    facilities: ["Parking", "Wheelchair Access"],
    paymentMethods: ["Cash", "Insurance", "NHIS Card"],
    about: "Main hospital serving Makeni and Northern Province with general medical and emergency services.",
  },
  {
    id: "10",
    name: "Koidu Government Hospital",
    type: "Hospital",
    category: "Government",
    rating: 3.8,
    reviewCount: 97,
    verified: true,
    address: "Koidu Town, Kono",
    district: "Kono",
    region: "Eastern Province",
    phone: "076-555-0010",
    hours: "Open 24/7",
    is24Hours: true,
    isOpenNow: true,
    emergency: true,
    services: ["Emergency Care", "Surgery", "Maternity Services", "Laboratory Tests", "Pharmacy", "Vaccination"],
    facilities: ["Parking", "Generator"],
    paymentMethods: ["Cash", "NHIS Card"],
    about: "Government hospital serving Kono district with essential medical services and emergency care.",
  },
  // Health Centers
  {
    id: "11",
    name: "Lumley Health Centre",
    type: "Health Center",
    category: "Government",
    rating: 3.7,
    reviewCount: 89,
    verified: true,
    address: "Cape Road, Lumley, Freetown",
    district: "Western Urban",
    region: "Western Area",
    phone: "076-555-0011",
    hours: "Mon-Fri: 8:00 AM - 5:00 PM, Sat: 9:00 AM - 1:00 PM",
    is24Hours: false,
    isOpenNow: true,
    emergency: false,
    services: ["Outpatient Services", "Vaccination", "Malaria Treatment", "Child Healthcare", "Laboratory Tests"],
    facilities: ["Waiting Area", "Pharmacy"],
    paymentMethods: ["Cash", "NHIS Card"],
    about: "Community health center providing primary healthcare services to Lumley and surrounding areas.",
  },
  {
    id: "12",
    name: "Waterloo Health Centre",
    type: "Health Center",
    category: "Government",
    rating: 3.6,
    reviewCount: 72,
    verified: true,
    address: "Main Street, Waterloo",
    district: "Western Rural",
    region: "Western Area",
    phone: "076-555-0012",
    hours: "Mon-Fri: 8:00 AM - 5:00 PM",
    is24Hours: false,
    isOpenNow: true,
    emergency: false,
    services: [
      "Outpatient Services",
      "Vaccination",
      "Maternity Services",
      "Child Healthcare",
      "HIV/AIDS Testing & Treatment",
    ],
    facilities: ["Waiting Area", "Maternity Ward"],
    paymentMethods: ["Cash", "NHIS Card"],
    about: "Health center serving Waterloo with focus on maternal and child health services.",
  },
  // Clinics
  {
    id: "13",
    name: "SOS Clinic",
    type: "Clinic",
    category: "Private",
    rating: 4.6,
    reviewCount: 156,
    verified: true,
    address: "Wilkinson Road, Freetown",
    district: "Western Urban",
    region: "Western Area",
    phone: "076-555-0013",
    email: "info@sosclinic.sl",
    hours: "Mon-Sat: 8:00 AM - 7:00 PM",
    is24Hours: false,
    isOpenNow: true,
    emergency: false,
    services: ["Outpatient Services", "Laboratory Tests", "Pharmacy", "Dental Services", "Eye Care"],
    facilities: ["Air Conditioning", "WiFi", "Parking"],
    paymentMethods: ["Cash", "Credit Card", "Mobile Money"],
    about: "Modern private clinic offering quality outpatient services with short waiting times.",
  },
  {
    id: "14",
    name: "Medilinks Clinic",
    type: "Clinic",
    category: "Private",
    rating: 4.5,
    reviewCount: 134,
    verified: true,
    address: "Spur Road, Freetown",
    district: "Western Urban",
    region: "Western Area",
    phone: "076-555-0014",
    email: "info@medilinks.sl",
    hours: "Mon-Fri: 8:00 AM - 6:00 PM, Sat: 9:00 AM - 2:00 PM",
    is24Hours: false,
    isOpenNow: true,
    emergency: false,
    services: ["Outpatient Services", "Laboratory Tests", "Pharmacy", "Vaccination"],
    facilities: ["Air Conditioning", "Parking"],
    paymentMethods: ["Cash", "Credit Card", "Insurance"],
    about: "Professional clinic providing comprehensive outpatient and diagnostic services.",
  },
  {
    id: "15",
    name: "Healthway Clinic",
    type: "Clinic",
    category: "Private",
    rating: 4.3,
    reviewCount: 98,
    verified: true,
    address: "Old Railway Line, Freetown",
    district: "Western Urban",
    region: "Western Area",
    phone: "076-555-0015",
    hours: "Mon-Sun: 8:00 AM - 8:00 PM",
    is24Hours: false,
    isOpenNow: true,
    emergency: false,
    services: ["Outpatient Services", "Laboratory Tests", "Pharmacy", "Mental Health"],
    facilities: ["Air Conditioning", "WiFi"],
    paymentMethods: ["Cash", "Mobile Money"],
    about: "Accessible clinic offering medical and mental health services with extended hours.",
  },
  // Pharmacies
  {
    id: "16",
    name: "City Pharmacy",
    type: "Pharmacy",
    category: "Private",
    rating: 4.2,
    reviewCount: 87,
    verified: true,
    address: "Siaka Stevens Street, Freetown",
    district: "Western Urban",
    region: "Western Area",
    phone: "076-555-0016",
    hours: "Mon-Sat: 8:00 AM - 8:00 PM, Sun: 10:00 AM - 4:00 PM",
    is24Hours: false,
    isOpenNow: true,
    emergency: false,
    services: ["Pharmacy"],
    facilities: ["Air Conditioning"],
    paymentMethods: ["Cash", "Mobile Money", "Credit Card"],
    about: "Well-stocked pharmacy in central Freetown offering prescription and over-the-counter medications.",
  },
  {
    id: "17",
    name: "MedPlus Pharmacy",
    type: "Pharmacy",
    category: "Private",
    rating: 4.4,
    reviewCount: 102,
    verified: true,
    address: "Wilkinson Road, Freetown",
    district: "Western Urban",
    region: "Western Area",
    phone: "076-555-0017",
    hours: "Mon-Fri: 8:00 AM - 7:00 PM, Sat: 9:00 AM - 5:00 PM",
    is24Hours: false,
    isOpenNow: true,
    emergency: false,
    services: ["Pharmacy", "Laboratory Tests"],
    facilities: ["Air Conditioning", "WiFi"],
    paymentMethods: ["Cash", "Mobile Money", "Credit Card", "Insurance"],
    about: "Professional pharmacy with pharmaceutical consultation and basic lab services.",
  },
  // Laboratories
  {
    id: "18",
    name: "Diagnostic Centre",
    type: "Laboratory",
    category: "Private",
    rating: 4.5,
    reviewCount: 123,
    verified: true,
    address: "Fourah Bay Road, Freetown",
    district: "Western Urban",
    region: "Western Area",
    phone: "076-555-0018",
    email: "info@diagnosticcentre.sl",
    hours: "Mon-Fri: 7:00 AM - 6:00 PM, Sat: 8:00 AM - 2:00 PM",
    is24Hours: false,
    isOpenNow: true,
    emergency: false,
    services: ["Laboratory Tests", "HIV/AIDS Testing & Treatment"],
    facilities: ["Air Conditioning", "Parking"],
    paymentMethods: ["Cash", "Credit Card", "Insurance", "Mobile Money"],
    about: "Modern diagnostic laboratory offering comprehensive testing services with quick turnaround times.",
  },
  {
    id: "19",
    name: "LifeLab Diagnostic Center",
    type: "Laboratory",
    category: "Private",
    rating: 4.3,
    reviewCount: 94,
    verified: true,
    address: "Congo Cross, Freetown",
    district: "Western Urban",
    region: "Western Area",
    phone: "076-555-0019",
    hours: "Mon-Sat: 7:30 AM - 5:00 PM",
    is24Hours: false,
    isOpenNow: true,
    emergency: false,
    services: ["Laboratory Tests", "Malaria Treatment"],
    facilities: ["Air Conditioning"],
    paymentMethods: ["Cash", "Mobile Money"],
    about: "Reliable laboratory providing accurate test results for various medical conditions.",
  },
  {
    id: "20",
    name: "Bonthe District Hospital",
    type: "Hospital",
    category: "Government",
    rating: 3.7,
    reviewCount: 65,
    verified: true,
    address: "Bonthe Town, Bonthe",
    district: "Bonthe",
    region: "Southern Province",
    phone: "076-555-0020",
    hours: "Open 24/7",
    is24Hours: true,
    isOpenNow: true,
    emergency: true,
    services: ["Emergency Care", "Maternity Services", "Malaria Treatment", "Laboratory Tests", "Pharmacy"],
    facilities: ["Generator", "Boat Access"],
    paymentMethods: ["Cash", "NHIS Card"],
    about: "Island hospital serving Bonthe district with essential medical services.",
  },
]

export interface HealthAlert {
  id: string
  type: "Outbreak" | "Vaccination" | "Health Tip" | "COVID-19" | "Emergency"
  severity: "Critical" | "Warning" | "Info"
  title: string
  summary: string
  content: string
  districts: string[]
  datePosted: string
  actions: string[]
  contacts: { label: string; value: string }[]
  resources?: { title: string; url: string }[]
}

export const demoHealthAlerts: HealthAlert[] = [
  {
    id: "1",
    type: "Vaccination",
    severity: "Info",
    title: "Free Yellow Fever Vaccination - National Campaign",
    summary: "Free yellow fever vaccination for all citizens. Visit your nearest health center with your ID card.",
    content:
      "The Ministry of Health is conducting a nationwide yellow fever vaccination campaign from January 15-30, 2025. All citizens are encouraged to get vaccinated free of charge at designated health centers across the country.",
    districts: ["All Districts"],
    datePosted: "2 days ago",
    actions: [
      "Visit your nearest health center",
      "Bring your ID card or birth certificate",
      "Get vaccinated between 8 AM - 5 PM",
      "Receive your vaccination card",
    ],
    contacts: [
      { label: "Ministry of Health Hotline", value: "117" },
      { label: "Campaign Coordinator", value: "076-555-1000" },
    ],
    resources: [
      { title: "Vaccination Centers List", url: "#" },
      { title: "Yellow Fever Facts (PDF)", url: "#" },
    ],
  },
  {
    id: "2",
    type: "Outbreak",
    severity: "Critical",
    title: "Cholera Cases Reported in Western Area",
    summary:
      "Cholera cases have been reported in Western Urban and Rural areas. Take immediate precautions and report symptoms immediately.",
    content:
      "The Ministry of Health has confirmed several cases of cholera in Western Urban and Western Rural districts. Citizens are urged to take preventive measures including drinking only safe water, washing hands frequently, and cooking food thoroughly.",
    districts: ["Western Urban", "Western Rural"],
    datePosted: "5 hours ago",
    actions: [
      "Drink only boiled or bottled water",
      "Wash hands with soap frequently",
      "Cook food thoroughly, especially seafood",
      "Report symptoms immediately: severe diarrhea, vomiting, dehydration",
      "Visit nearest health center if symptoms appear",
    ],
    contacts: [
      { label: "Emergency Hotline", value: "117" },
      { label: "Cholera Treatment Center", value: "076-555-2000" },
      { label: "Connaught Hospital", value: "076-555-0001" },
    ],
    resources: [
      { title: "Cholera Prevention Guide", url: "#" },
      { title: "Treatment Centers Map", url: "#" },
    ],
  },
  {
    id: "3",
    type: "Health Tip",
    severity: "Info",
    title: "Rainy Season Malaria Prevention",
    summary: "Protect yourself from malaria during rainy season. Use mosquito nets and eliminate standing water.",
    content:
      "As we enter the rainy season, the risk of malaria increases. Sleep under treated mosquito nets, especially children and pregnant women. Drain standing water around your home and seek immediate treatment if you have fever, chills, or body aches.",
    districts: ["All Districts"],
    datePosted: "1 week ago",
    actions: [
      "Sleep under insecticide-treated mosquito nets",
      "Drain standing water around your home",
      "Use mosquito repellent",
      "Seek treatment immediately if symptoms appear",
      "Pregnant women should attend antenatal care regularly",
    ],
    contacts: [
      { label: "Malaria Hotline", value: "117" },
      { label: "Free Nets Distribution", value: "076-555-3000" },
    ],
    resources: [
      { title: "Malaria Prevention Guide (PDF)", url: "#" },
      { title: "Treatment Centers", url: "#" },
    ],
  },
  {
    id: "4",
    type: "COVID-19",
    severity: "Warning",
    title: "COVID-19 Booster Shots Available",
    summary: "COVID-19 booster shots now available at major health centers. Get your booster to stay protected.",
    content:
      "COVID-19 booster shots are now available for all adults who received their second dose at least 6 months ago. Visit designated vaccination centers to receive your booster shot free of charge.",
    districts: ["All Districts"],
    datePosted: "3 days ago",
    actions: [
      "Check if you're eligible (6+ months after 2nd dose)",
      "Visit vaccination center with your vaccination card",
      "Receive booster shot",
      "Wait 15 minutes after vaccination",
    ],
    contacts: [
      { label: "COVID-19 Hotline", value: "117" },
      { label: "Vaccination Info", value: "076-555-4000" },
    ],
  },
  {
    id: "5",
    type: "Health Tip",
    severity: "Info",
    title: "World Breastfeeding Week",
    summary: "Support breastfeeding mothers! Breast milk provides best nutrition for babies in first 6 months.",
    content:
      "This World Breastfeeding Week, we celebrate the importance of breastfeeding. Exclusive breastfeeding for the first 6 months provides optimal nutrition and protection against diseases for babies.",
    districts: ["All Districts"],
    datePosted: "4 days ago",
    actions: [
      "Breastfeed exclusively for first 6 months",
      "Seek support from healthcare workers if needed",
      "Attend breastfeeding support groups",
      "Employers should provide breastfeeding breaks",
    ],
    contacts: [
      { label: "Lactation Support", value: "076-555-5000" },
      { label: "PCMH Maternity", value: "076-555-0003" },
    ],
    resources: [
      { title: "Breastfeeding Guide (PDF)", url: "#" },
      { title: "Support Groups", url: "#" },
    ],
  },
  {
    id: "6",
    type: "Emergency",
    severity: "Critical",
    title: "Heatwave Health Advisory",
    summary: "Extreme heat expected this week. Stay hydrated and avoid prolonged sun exposure.",
    content:
      "Temperatures are expected to reach extreme levels this week. The Ministry of Health advises staying hydrated, avoiding sun exposure during peak hours (11 AM - 3 PM), and checking on elderly neighbors.",
    districts: ["Western Urban", "Bo", "Makeni", "Kenema"],
    datePosted: "1 day ago",
    actions: [
      "Drink plenty of water throughout the day",
      "Avoid outdoor activities 11 AM - 3 PM",
      "Wear light-colored, loose clothing",
      "Check on elderly and vulnerable people",
      "Seek medical help for heat exhaustion symptoms",
    ],
    contacts: [{ label: "Emergency Hotline", value: "117" }],
  },
  {
    id: "7",
    type: "Vaccination",
    severity: "Info",
    title: "Polio Vaccination Campaign for Children",
    summary: "Free polio vaccination for children under 5 years. Protect your child from polio.",
    content:
      "National polio vaccination campaign targeting all children under 5 years old. Vaccination teams will visit door-to-door, or visit your nearest health center.",
    districts: ["All Districts"],
    datePosted: "1 week ago",
    actions: [
      "Ensure your child under 5 is vaccinated",
      "Receive vaccination teams at your door",
      "Or visit nearest health center",
      "Keep vaccination card safe",
    ],
    contacts: [{ label: "Immunization Hotline", value: "076-555-6000" }],
  },
  {
    id: "8",
    type: "Health Tip",
    severity: "Info",
    title: "Mental Health Awareness Month",
    summary: "Mental health matters. Seek help if you're struggling. You're not alone.",
    content:
      "October is Mental Health Awareness Month. Mental health is just as important as physical health. If you're experiencing depression, anxiety, or other mental health issues, professional help is available.",
    districts: ["All Districts"],
    datePosted: "2 weeks ago",
    actions: [
      "Talk to someone you trust",
      "Seek professional help - it's not weakness",
      "Call mental health hotline for support",
      "Practice self-care daily",
    ],
    contacts: [
      { label: "Mental Health Hotline", value: "076-555-7000" },
      { label: "Crisis Support", value: "117" },
    ],
    resources: [
      { title: "Mental Health Guide (PDF)", url: "#" },
      { title: "Support Groups", url: "#" },
    ],
  },
]
